# Sponsor this project
github: ExpertVagabond
patreon: expertvagabond
open_collective: expertvagabond
ko_fi: expertvagabond
tidelift: npm/expertvagabond
community_bridge: expertvagabond
liberapay: expertvagabond
issuehunt: ExpertVagabond
custom: ["https://buymeacoffee.com/expertvagabond"]
